server:
  port: 8033
spring:
  cloud:
    schemaRegistryClient:
      endpoint: http://localhost:8081
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
        alert-output:
          destination: alert10
          binder: kafka
        asset-output:
          destination: asset003
          binder: kafka
      kafka:
        binder:
          autoAddPartitions: true
          brokers: localhost:9092
          producer-properties:
            partition-count: 2
            key.serializer: org.apache.kafka.common.serialization.LongSerializer
            value.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
